### ISSUE TITLE
another possible and portable way to instantiate a class

### ISSUE THREAD

**Issue by henri-tremblay** [easymock/objenesis#23]
Original [issue 20](https://code.google.com/p/objenesis/issues/detail?id=20) created by henri-tremblay on 2013-08-16T08:01:07.000Z:

If the original class is not final you can create a class that extends it, creating direct JVM byte-code, and loading the created class. Then creating an instance of the extended class will invoke the constructor of the extending class, but since the JVM code is generated calling the superconstructor can be skipped (simply not generating the code into the constructor that invokes super).

You may perhaps even create the extending class if the original class is final accessing the original class object already loaded and altering the &quot;final&quot; modifier using reflection.

**Comment by henri-tremblay** [comment]
Indeed, just removing the constructor of the super class causes a VerifyError. I will now try to call the constructor of Object.

**Comment by henri-tremblay** [comment]
In fact, it does work when `-Xverify:none` is used

**Comment by jcarvalho** [comment]
A similar approach to this one is to synthesize the `ObjectInstantiator` instance, so it does what you attempted (manually invoking the desired constructor), and having it extend `sun.reflect.MagicAccessorImpl`, as its subclasses are not subject to the regular bytecode verification, and allow you to do it without globally disabling the verifier.

I have a working prototype of this, and despite not having tested it in any platform other than Hotspot, it seems to work great.

**Comment by jcarvalho** [comment]
(I know this is not portable, just wanted to share another approach that I haven't seen explored yet)

**Comment by henri-tremblay** [comment]
MagicAccessorImpl is package scope. You generate the ObjectInstantiator? Can you share the prototype in a gist or github repo?

**Comment by henri-tremblay** [comment]
Objenesis isn't supposed to have portable instantiators. It is supposed to work on any platform. Right now, the only none working platform I am aware of if Google App Engine.

**Comment by jcarvalho** [comment]
`MagicAccessorImpl` is package scope yes, however, its 'no verifier' property means you can create subclasses outside of the package.

You can find the prototype [here](https://github.com/jcarvalho/magic-instantiator). The interesting part is in the [MagicInstantiatorStrategy](https://github.com/jcarvalho/magic-instantiator/blob/master/src/main/java/io/github/jcarvalho/MagicInstantiatorStrategy.java) class.

I am using ASM to generate the `ObjectInstantiator` instance. This is a relatively performance-heavy operation, but seeing as instantiator instances are cached by default, this should provide performance similar to the other instantiators.

**Comment by henri-tremblay** [comment]
How cute. You can generate a class extending it but not extend it from source code :-)

Thanks for the code. I will try it ASAP.

Can you tell me why or on which platform we are using it? (so why the classical instantiators where not working)

**Comment by jcarvalho** [comment]
I wrote this when searching for an alternative to Sun's `ReflectionFactory`, first attempted something similar to what you attempted in this issue, and stumbled upon the 'magic' solution.

It was only when I saw you attempting this and failing that I ported it to Objenesis. It will probably only work on the same platforms as ReflectionFactory, it is simply another approach.

**Comment by henri-tremblay** [comment]
I've forked your idea in a issue #35
