### ISSUE TITLE
Add Security Policy

### ISSUE THREAD

**Issue by gabibguti** [easymock/objenesis#238]
Adding a Security Policy is important to provide guidance on how users can report potential vulnerabilities and also raise awareness of when vulnerabilities will be confirmed, fixed and disclosed.

Following up on @joycebrum security recommendation at https://github.com/easymock/objenesis/issues/177, this one also related to security and recommended by [Github](https://docs.github.com/en/code-security/getting-started/securing-your-repository#setting-a-security-policy) and [Scorecard](https://github.com/ossf/scorecard).

If you agree, I can open a PR to suggest a Security Policy. We can then work together to communicate how the repo can best handle vulnerability reports if you think it's applicable.

##### Additional Context
Hi! I'm Gabriela and I work on behalf of Google and the OpenSSF suggesting supply-chain security changes :)

**Comment by henri-tremblay** [comment]
Sure. The answer to that is probably for people to send me an email.

**Comment by henri-tremblay** [comment]
Ok. I have enable github and added a SECURITY.md. Please tell me if something else is needed.

**Comment by gabibguti** [comment]
All good.
