### ISSUE TITLE
Reference actions by commit SHA

### ISSUE THREAD

**Issue by gabibguti** [easymock/objenesis#239]
Referencing actions by commit SHA in GitHub workflows guarantees you are using an immutable version. Actions referenced by tags and branches are more vulnerable to attacks, such as the tag being moved to a malicious commit or a malicious commit being pushed to the branch.

Although there are pros and cons for each reference, GitHub understands [using commit SHAs is more reliable](https://docs.github.com/en/actions/learn-github-actions/finding-and-customizing-actions#using-shas), as does [Scorecard](https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies) security tool.

Like [adding a security policy](https://github.com/easymock/objenesis/issues/238) and [setting minimum permissions in GitHub workflows](https://github.com/easymock/objenesis/issues/177), this change is also a security good-practice. If you agree, we can update, for example: `actions/checkout@v4` to `actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11` followed by a comment `# v4.1.1` to keep the version readable and I can support you by opening a PR.

##### Additional Context

Hi again! I'm Gabriela and I work on behalf of Google and the OpenSSF suggesting supply-chain security changes :)

**Comment by henri-tremblay** [comment]
Please go ahead with the PR.
