### ISSUE TITLE
New MagicInstantiator using MagicAccessorImpl

### ISSUE THREAD

**Issue by henri-tremblay** [easymock/objenesis#35]
New issue created from issue #23 comment https://github.com/easymock/objenesis/issues/23#issuecomment-124518907

Synthesize the ObjectInstantiator instance, so it does what you attempted (manually invoking the desired constructor), and having it extend sun.reflect.MagicAccessorImpl, as its subclasses are not subject to the regular bytecode verification, and allow you to do it without globally disabling the verifier.

`MagicAccessorImpl` is package scope, however, its 'no verifier' property means you can create subclasses outside of the package.

You can find the prototype [here](https://github.com/jcarvalho/magic-instantiator). The interesting part is in the [MagicInstantiatorStrategy](https://github.com/jcarvalho/magic-instantiator/blob/master/src/main/java/io/github/jcarvalho/MagicInstantiatorStrategy.java) class.

I am using ASM to generate the `ObjectInstantiator` instance. This is a relatively performance-heavy operation, but seeing as instantiator instances are cached by default, this should provide performance similar to the other instantiators.

**Comment by henri-tremblay** [comment]
It's working perfectly. Sadly, MagicAccessorImpl isn't present on Google App Engine so this instantiator doesn't work either

**Comment by jcarvalho** [comment]
Perhaps there is another GAE-specific class that will trigger the same behavior?

I'm not sure if the code for the JVM running on GAE is open-source, if it is, it may not be so hard to find.

**Comment by henri-tremblay** [comment]
From as far as I know, it's not available. We will need to have help from Google to find a solution.

**Comment by henri-tremblay** [comment]
The magic instantiator is now merge into objenesis

**Comment by henri-tremblay** [comment]
@jcarvalho BTW, I don't know if you had a look at the final version. Instead of having a special strategy, I'm using delegation in the instantiator to create the magic one
