### ISSUE TITLE
Android N : standard android instantiators don't work.

### ISSUE THREAD

**Issue by narayank** [easymock/objenesis#37]
The private ObjectStreamClass APIs that objensis depends on don't exist any longer. Please use sun.misc.unsafe.allocateInstance on Android N and above.

That method has the same semantics as the JNI AllocObject method (object constructors aren't run).

**Comment by henri-tremblay** [comment]
Thanks for telling me. I will do the modification ASAP.

**Comment by henri-tremblay** [comment]
Fixed using #38
