### ISSUE TITLE
Objenesis license incompatible with EPL

### ISSUE THREAD

**Issue by sophokles73** [easymock/objenesis#40]
Hi,

I am working on several Eclipse projects where we would like to use Mockito 1.9 which depends on Objenesis 1.0. The Eclipse Foundation has very strict rules regarding IP and license validation. In particular, a scan of the source code of third party dependencies is conducted before an Eclipse project can use it. In case of Objenesis 1.0 this has brought up a problem with the JRockit support classes which are licensed for use only under a license approved by the FSF (which the Eclipse Public License unfortunately is not). This makes it very hard for Eclipse Projects to even use Mockito and Objenesis for testing (not to mention re-distribute it). Some people have started to *strip* out the offending classes and keep a copy of the modified source code in their projects.

Is there a way to either get approval from the original authors to license the code under less restrictive terms or, if not, to isolate the *offending* classes in a separate (optional) module?
This way using Objenesis would be much more convenient for the many Eclipse projetcs to use ..

Regards,
Kai

**Comment by henri-tremblay** [comment]
You guys have quite motivated lawyers. The copyright is from BEA which is now Oracle. The code was done by @mrbubble. I don't remember why the copyright was added. 

But I think I will simplify and just remove this instantiator. It was used for a very old version of JRockit anyway so I don't think anybody will ever use it anymore.

**Comment by sophokles73** [comment]
@henri-tremblay that sounds great :-) Thanks a lot! Any idea when you want to release 2.4?

**Comment by henri-tremblay** [comment]
As soon as possible. Even if this is the only fix.

**Comment by sophokles73** [comment]
Ok, thanks again. This will make our lives a lot easier :-)
