### ISSUE TITLE
org.objenesis:objenesis-parent:pom:2.5 is missing in JCenter Maven repo

### ISSUE THREAD

**Issue by grimsa** [easymock/objenesis#50]
I have a project where I'm using Mockito 2.6.3+, which depends on Objenesis 2.5.
We're using JCenter as central Maven repository and now our build is failing with this error:
```
Failed to read artifact descriptor for org.objenesis:objenesis:jar:2.5:
    Could not find artifact org.objenesis:objenesis-parent:pom:2.5 in central
```

I can see version 2.5 distribution here: https://bintray.com/easymock/distributions/objenesis , but not in the Maven repo.

Maven central: http://central.maven.org/maven2/org/objenesis/objenesis-parent/
JCenter: http://jcenter.bintray.com/org/objenesis/objenesis-parent/

Is JCenter also covered by the release process? If not, is it JCenter support that can fix it?

**Comment by henri-tremblay** [comment]
Thanks for telling me. There is indeed something wrong here. I've reach out for support and hopefully it should be solved soon.

**Comment by henri-tremblay** [comment]
The pom is now there
