### ISSUE TITLE
Android18Instantiator Fails On Android O

### ISSUE THREAD

**Issue by erandagan** [easymock/objenesis#52]
It seems that `Android18Instantiator` does not work on Android O beta (SDK level 25).
Looks like Android dropped support for `ObjectStreamClass.getConstructorId`

```
Caused by java.lang.UnsupportedOperationException: ObjectStreamClass.getConstructorId(Class<?>) is not supported on SDK 25
       at java.io.ObjectStreamClass.getConstructorId(ObjectStreamClass.java:2294)
       at java.lang.reflect.Method.invoke(Method.java)
       at org.objenesis.instantiator.android.Android18Instantiator.findConstructorIdForJavaLangObjectConstructor(Android18Instantiator.java:72)
       at org.objenesis.instantiator.android.Android18Instantiator.(Android18Instantiator.java:39)
       at org.objenesis.strategy.StdInstantiatorStrategy.newInstantiatorOf(StdInstantiatorStrategy.java:96)
...
```

**Comment by henri-tremblay** [comment]
They love to make my life complicated. :-) Thanks for reporting. I will look into it. The fix should be out soon.

**Comment by henri-tremblay** [comment]
@erandagan Stupid question. I'm looking for the Android O SDK and system image to run with AVD. Can you help me?

**Comment by erandagan** [comment]
@henri-tremblay Sure, I'll see if I can find it. I got the stack traces from my app's users which installed the O Beta on their devices.

**Comment by westnordost** [comment]
The Android O System Image for the Android Emulator is listed in the SDK manager under _Android O Preview_ as _Google APIs Intel x86 Atom System Image_. But only for the Android Studio 3.0.
See https://developer.android.com/preview/migration.html#pct

If you have Android Studio already installed, you can change to the canary channel to (probably?) update to 3.0. See https://developer.android.com/studio/intro/update.html##sdk-manager

**Comment by henri-tremblay** [comment]
Thanks. I was using the Android plugin on IntelliJ Ultimate. Always disappointing to see that there are so much things missing in it. But yes, using Android Studio Canary made it appear. So I'm almost there now.

**Comment by henri-tremblay** [comment]
I just realized something. You are not supposed to use Android18Instantiator anymore. Latest Android versions (N and O) are based on the OpenJDK and so are using the `UnsafeFactoryInstantiator`. This is the one `StdInstantiatorStrategy` will give you.

So I just tested it on Android O and it works perfectly.
