### ISSUE TITLE
Please remove the hidden .mvn directory from the source tarball

### ISSUE THREAD

**Issue by apoleon** [easymock/objenesis#57]
Hi,

please consider to remove the hidden .mvn/wrapper directory and the included jar file from the source releases. It is actually not needed to build objenesis and comes without source and thus has to be removed when it is distributed by Debian or other distributions.

**Comment by henri-tremblay** [comment]
Can you tell me which jar exactly?

**Comment by apoleon** [comment]
Am 26.06.2017 um 01:11 schrieb Henri Tremblay:
> Can you tell me which jar exactly?

It's this one.

https://github.com/easymock/objenesis/blob/master/.mvn/wrapper/maven-wrapper.jar

**Comment by apoleon** [comment]
Prebuilt jar files should never be part of any source release. Debian requires source code for everything that should be shipped in its main distribution. A jar file with class files is obviously not source. We either need the corresponding *.java files or I have to repack the tarball and remove it. Our upstream guide sums it up:

https://wiki.debian.org/UpstreamGuide

I'm quite sure there is a way in Github to exclude files before they are included in the release tarballs. Jars just increase the size of the tarball and Linux distributions will always build Objenesis with the packaged Maven version anyway. I had no problems with building the latest release without the maven-wrapper.jar.

**Comment by henri-tremblay** [comment]
In general it works. But nothing is guaranteed. I get what Debian needs. But it means to be less nice for everyone else. I'm looking for exclusions on the github git archive. Is it complicated for you to ignore?

**Comment by henri-tremblay** [comment]
Ok. I should have fixed it. Can you do a git archive from HEAD (or a tag that I create) or I need to do an actual release?

**Comment by apoleon** [comment]
Am 26.06.2017 um 05:54 schrieb Henri Tremblay:
> Ok. I should have fixed it. Can you do a git archive from HEAD (or a tag
> that I create) or I need to do an actual release?

You don't need to do a new release just because of this bug. But it
would be nice if the jar was no longer included in the source tarball
when you do your next release.

**Comment by henri-tremblay** [comment]
Excellent. Should be the case
