### ISSUE TITLE
ClassDefinitionUtils doesn't compile with Java 11

### ISSUE THREAD

**Issue by ebourg** [easymock/objenesis#61]
ClassDefinitionUtils.defineClass() uses the Unsafe.defineClass() method which was removed in Java 11:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project objenesis: Compilation failure
[ERROR] ~/objenesis/main/src/main/java/org/objenesis/instantiator/util/ClassDefinitionUtils.java:[100,54] cannot find symbol
[ERROR]   symbol:   method defineClass(java.lang.String,byte[],int,int,java.lang.ClassLoader,java.security.ProtectionDomain)
[ERROR]   location: class sun.misc.Unsafe
```

**Comment by henri-tremblay** [comment]
Thanks. I'm aware of it. Should have filed it. I'm on it right now. If you have a PR for that, I'm listening.

Useful resources are:
https://dzone.com/articles/jdk-11-and-proxies-in-a-world-past-sunmiscunsafe
https://github.com/jboss-javassist/javassist/pull/198/files
https://github.com/gradle/gradle/pull/4976/files

**Comment by ebourg** [comment]
Thank you!
