### ISSUE TITLE
Compilation error: ObjenesisTest.java:[68,7] cannot find symbol method assertThrows

### ISSUE THREAD

**Issue by apoleon** [easymock/objenesis#74]
I am trying to package the latest version 3.1 of objenesis for Debian. When I try to compile it, I get a compilation error in ObjenesisTest.java because of the unknown method assertThrows. AFAIK assertThrows only exists in Junit5 but Objenesis uses Junit4.

**Comment by henri-tremblay** [comment]
No. It is available in JUnit 4.13 (still beta)

**Comment by apoleon** [comment]
Ok, sorry then for the noise. We don't package beta releases of junit, so I had to remove the test for now.
