### ISSUE TITLE
Objenesis can't be compiled on Android SDK < 26

### ISSUE THREAD

**Issue by henri-tremblay** [easymock/objenesis#79]
See https://github.com/mockito/mockito/issues/2007.

The current possible solution can be to remove "exotic" instantiator from objenesis-core. We should have a test to make sure it works.

**Comment by yogurtearl** [comment]
@henri-tremblay  The main issue for supporting android SDK < 26 is any mention of `MethodHandle` in the bytecode. 

The Java 11 support added this and broke Android. 
https://github.com/easymock/objenesis/commit/5f9d20b5aa1223217ff79f74acffe1c2bc67899a

I think it will be hard to have a single jar that works on android SDK < 26 and JDK 11+.

Providing multiple different artifacts is one possible solultion. Perhaps with a `-jdk7` and `-jdk11` maven classifier?

**Comment by henri-tremblay** [comment]
I'm a bit overwhelm these day. I do hope I will have the time to revisit soon. If anyone has the time, feel free to look.

**Comment by henri-tremblay** [comment]
I have pushed the changes moving some instantiators in a new project. Could you please check if it works? I'm still not sure it's a good idea. JPMS requires me to change the package of the moved classes. I'm afraid of what I will break but I hope they are not that used. The alternative is indeed to play with classifiers.
