### ISSUE TITLE
Copyright and Owner is missing in license

### ISSUE THREAD

**Issue by ts-twt** [easymock/objenesis#83]
https://github.com/easymock/objenesis/blob/997300adb95f28e449c8da0811f2da125b5663c0/LICENSE.txt#L190

**Comment by henri-tremblay** [comment]
No need. That is just telling which template should be applied to other files. It's fine the way it see [Spring equivalent](https://github.com/spring-projects/spring-framework/blob/master/LICENSE.txt) for instance.
