### ISSUE TITLE
`org.objenesis:objenesis-test` missing in Maven Central

### ISSUE THREAD

**Issue by ViteFalcon** [easymock/objenesis#85]
According to Maven Central, [`org.objenesis:objenesis:3.2`](https://search.maven.org/artifact/org.objenesis/objenesis/3.2/jar) has a dependency on `org.objenesis:objenesis-test` but that dependency [does not exist in Maven Central](https://search.maven.org/artifact/org.objenesis/objenesis-test).

I'm guessing this is a miss since `org.objenesis:objenesis-test` is a new dependency starting from 3.2 judging from fact that [`3.1` does not have that dependency](https://search.maven.org/artifact/org.objenesis/objenesis/3.1/jar).

Would you please publish the 3.2 version of `org.objenesis:objenesis-test` package to Maven? Thank you for taking the time to look at this.

**Comment by henri-tremblay** [comment]
The dependency is in test scope. It wasn't deployed on purpose. How is it causing an issue?
